window.POE2_LOCATION_DATA = {
  source: "https://www.poe2wiki.net/wiki/List_of_maps",
  updated: "2026-06-21",
  maps: [
    ["Alpine Ridge", "map", "Mountain", "Gelida, the Frost-Tongue / Ignatia, the Flame-Sworn"],
    ["Arid Plains", "map", "Desert", "Akthi, the Final Sting / Anundr, the Sandworm"],
    ["Augury", "map", "Grass, Forest, Swamp", "Gressor-Kul, the Apex"],
    ["Azmerian Ranges", "map", "Mountain, Forest", "Morwyn, the Kinslayer"],
    ["Backwash", "map", "Forest, Swamp", "Yaota, the Loathsome"],
    ["Barren Atoll", "expedition", "Grand Expedition", "Kalguuran Expedition"],
    ["Bastille", "map", "", "Veynar, the Frostbane"],
    ["Bazaar", "map", "Vaal City", "Viper Napuatzi"],
    ["Bloodwood", "map", "Forest", "Gorian, the Moving Earth"],
    ["Blooming Field", "map", "Forest, Grass", "The Black Crow"],
    ["Bluff", "map", "Grass", "Gressor-Kul, the Apex"],
    ["Burial Bog", "map", "Swamp", "Grudgelash, Vile Ent"],
    ["Caldera", "map", "Ocean", "The Ravenous Fang"],
    ["Canal Hideout", "hideout", "Grass", ""],
    ["Canyon", "map", "Desert", "Morvak, the Infernal"],
    ["Castaway", "expedition", "Grand Expedition", "Torrek of the Drowned Fleet"],
    ["Cenotes", "map", "Mountain", "Bahlak, the Sky Seer"],
    ["Channel", "map", "Faridun City", "Hask, the Fallen Son"],
    ["Charred Isle", "expedition", "Grand Expedition", "Kalguuran Expedition"],
    ["Bleached Shoals", "expedition", "Grand Expedition", "Pearlescent Amulets"],
    ["Cliffside", "map", "", "Brakkus, the Juggernaut"],
    ["Confluence", "map", "", "Manassa, the Serpent Queen"],
    ["Creek", "map", "Forest", "Tierney, the Hateful"],
    ["Crimson Shores", "map", "Water", "Volkhar, the Emberborn"],
    ["Craggy Peninsula", "expedition", "Grand Expedition", "Rarity and Rogue Exiles"],
    ["Crypt", "map", "Desert, Grass", "Meltwax, Mockery of Faith"],
    ["Decay", "map", "Grass, Forest, Swamp", "The Fungus Behemoth"],
    ["Deforestation", "map", "Forest", "Morwyn, the Kinslayer"],
    ["Deserted", "map", "Desert", "Lord of the Pit"],
    ["Digsite", "map", "Grass", "Aurelian, the Grand Adjudicator"],
    ["Epitaph", "map", "Grass", "Saphira, The Dread Consort"],
    ["Felled Hideout", "hideout", "Forest", ""],
    ["Flotsam", "map", "", "Malgor, the Nautilord"],
    ["Forge", "map", "Mountain, Desert", "Vastweld, the Colossal Guardian"],
    ["Fortress", "map", "Desert", "Pirasha, the Forgotten Prisoner"],
    ["Frozen Falls", "map", "Mountain", "Thraeven, Wing of Winter"],
    ["Gothic City", "map", "Ezomyte City", "Near Iron Citadel"],
    ["Greenhouse", "map", "Swamp", "Rootgrasp, the Hateful Forest"],
    ["Grimhaven", "map", "Ezomyte City", "Saphira, The Dread Consort"],
    ["Headland", "map", "Faridun City", "Hask, the Fallen Son"],
    ["Hidden Grotto", "map", "Mountain, Grass, Forest, Swamp", "Zar Wali, the Bone Tyrant"],
    ["Hive", "map", "Desert", "The Fungus Behemoth"],
    ["Hive Fortress", "special", "Breach Stronghold", "Breach"],
    ["Ice Cave", "map", "", "The Frostborn Fiend"],
    ["Limestone Hideout", "hideout", "Water", ""],
    ["Lofty Summit", "map", "Mountain", "Oloton, the Remorseless"],
    ["Lost Towers", "map", "Forest, Desert", "Chetza, the Feathered Plague"],
    ["Marrow", "map", "Desert, Mountain", "Zar Wali, the Bone Tyrant"],
    ["Mesa", "map", "Desert", "Karash, The Dune Dweller"],
    ["Mineshaft", "map", "Faridun City", "Vorrik, The Infernal Engineer"],
    ["Mire", "map", "Forest, Swamp", "Riona, Winter's Cackle"],
    ["Molten Vault", "map", "Mountain, Vaal City", "Gulzal, the Living Furnace"],
    ["Moor of the Fallen Skies", "expedition", "Grand Expedition", "Runestones"],
    ["Mournful Cliffside", "boss", "Expedition", "Vorana, Last to Fall"],
    ["Moment of Zen", "special", "Water", "Nameless Seer"],
    ["Necropolis", "map", "Ezomyte City", "Tycho, the Black Praetor"],
    ["Oasis", "map", "Desert, Faridun City", "Ishtaroth, the Perennial"],
    ["Obscure Island", "boss", "Expedition", "Olroth, Origin of the Fall"],
    ["Ornate Chambers", "map", "Desert", "Serath, the Scaled One"],
    ["Overgrown", "map", "", "Tetzcatl, the Blazing Guardian"],
    ["Penitentiary", "map", "Ezomyte City", "Incarnation of Death"],
    ["Pit", "map", "Mountain", "Brakkus, the Juggernaut"],
    ["Plantation", "map", "", "Varloch, the Ashen Lord"],
    ["Ravine", "map", "Mountain, Faridun City", "Tetzcatl, the Blazing Guardian"],
    ["Razed Fields", "map", "", "Ignatia / Gelida"],
    ["Reservoir", "map", "Forest", "Grudgelash, Vile Thorn"],
    ["Riverhold", "map", "Forest", "Thariel, the Umbral Wraith"],
    ["Riverside", "map", "Forest", "Zekoa, The Headcrusher"],
    ["Rockpools", "map", "", "Brughor, the Insatiable"],
    ["Rugosa", "map", "", "Syvora, Daughter of the Deep"],
    ["Rupture", "map", "", "Zekoa, The Headcrusher"],
    ["Rustbowl", "map", "Desert", "Gozen, Rebellious Rustlord"],
    ["Scorched Cay", "expedition", "Grand Expedition", "Increased Rarity"],
    ["Sacred Reservoir", "map", "", "Zahmir, the Blade Sovereign"],
    ["Sanctuary", "map", "", "Pirasha, the Forgotten Prisoner"],
    ["Sandspit", "map", "Water", "The Sandstrider"],
    ["Savannah", "map", "Grass, Desert", "Caedron, the Hyena Lord"],
    ["Seepage", "map", "Grass", "The Fungus Behemoth"],
    ["Secluded Temple", "boss", "Expedition", "Uhtred, the Stardrinker"],
    ["Shrine Hideout", "hideout", "Desert", ""],
    ["Sinking Spire", "map", "Swamp", "Stormgore"],
    ["Sinkhole", "map", "", "Yama The White"],
    ["Slash", "map", "Forest", "The Black Crow"],
    ["Sinter Rift", "map", "Desert", "Brughor, the Insatiable"],
    ["Slick", "map", "Mountain", "Vorrik, The Infernal Engineer"],
    ["Sloughed Gully", "expedition", "Grand Expedition", "Kalguuran Expedition"],
    ["Snowfall", "map", "", "Thariel, the Umbral Wraith"],
    ["Spider Woods", "map", "Forest", "Rootgrasp, the Hateful Forest"],
    ["Sprawling Jungle", "boss", "Expedition", "Medved, the Fallen Seer"],
    ["Spring", "map", "Grass", "Manassa, the Serpent Queen"],
    ["Steaming Springs", "map", "Grass", "Manassa, the Serpent Queen"],
    ["Steppe", "map", "Grass", "Gozen, Rebellious Rustlord"],
    ["Stagnant Basin", "expedition", "Grand Expedition", "Kalguuran Expedition"],
    ["Stone Altar", "expedition", "Grand Expedition", "Kalguuran Expedition"],
    ["Stronghold", "map", "", "The Shackled Horror"],
    ["Sulphuric Caverns", "map", "Desert, Mountain", "Lord of the Pit / The Bone Colossus"],
    ["Sump", "map", "Swamp", "Brakka, the Withered Crone"],
    ["Sun Temple", "map", "Vaal City", "Tonqui, Seer of the Sun"],
    ["The Assembly", "map", "Grass, Vaal City", "Tetzcatl, the Blazing Guardian"],
    ["The Black Cathedral", "boss", "Ritual", "The King in the Mists"],
    ["The Burning Monolith", "boss", "Pinnacle", "The Arbiter of Ash"],
    ["The Copper Citadel", "boss", "Faridun City", "Jamanra, the Abomination"],
    ["The Ezomyte Megaliths", "boss", "Forest, Grass", "Boss waves"],
    ["The Fractured Lake", "special", "Water", "Lake of Kalandra"],
    ["Exhumed Ruins", "expedition", "Grand Expedition", "Logbook Reveal"],
    ["Frigid Bluffs", "expedition", "Grand Expedition", "Classic Logbook encounter"],
    ["Grazed Prairy", "expedition", "Grand Expedition", "Experience, Beyond, Hoards"],
    ["The Iron Citadel", "boss", "Ezomyte City", "Count Geonor"],
    ["The Jade Isles", "map", "", "Manoki, the Chosen"],
    ["The Oasis", "expedition", "Grand Expedition", "Kalguuran Expedition"],
    ["The Silent Cave", "special", "Desert", "Essence boss"],
    ["The Viridian Wildwood", "special", "Forest, Swamp", "Omen Altars"],
    ["The Stone Citadel", "boss", "Vaal City", "Doryani, Royal Thaumaturge"],
    ["The Origin Tower", "boss", "Pinnacle", "The Arbiter of Ash"],
    ["Tomb of the Fallen King", "boss", "Expedition", "Styrn, Fallen Knight of Aldur"],
    ["Trenches", "map", "Swamp", "Gorian, the Moving Earth"],
    ["Untainted Paradise", "special", "Water", "Experience"],
    ["Vaal City", "map", "Vaal City", "Viper Napuatzi"],
    ["Vaults of Kamasa", "special", "Vaal City", "Chests"],
    ["Volcanic Warrens", "expedition", "Grand Expedition", "Kalguuran Expedition"],
    ["Wayward Isle", "map", "", "Lord of the Pit"],
    ["Wetlands", "map", "Swamp", "Caedron, the Hyena Lord"],
    ["Willow", "map", "Forest", "Connal, the Tormented"],
    ["Woodland", "map", "Forest", "Murtagh, the Engorged / Colm, the Rancorous"],
    ["Simulacrum of Delusion", "special", "Delirium", "Delirium encounter"],
    ["Vastiri Racecourse Hideout", "hideout", "", ""],
    ["Atziri's Temple", "boss", "Vaal", "Atziri, Queen of the Vaal"],
    ["Caer Tarth", "boss", "Expedition", "Olroth, Origin of the Fall"],
    ["Twisted Domain", "boss", "Breach", "Xesht, We That Are One"],
    ["The Crux of Nothingness", "boss", "Breach", "Xesht, We That Are One"],
    ["The Realmgate", "boss", "Pinnacle", "Pinnacle access"],
    ["The Tomb of the Exiled Marakesh", "boss", "Trial", "Zarokh, the Temporal"],
    ["The Well of Souls", "boss", "Trial", "Zarokh, the Temporal"],
    ["The Withered Hollow", "boss", "Delirium", "The Simulacrum bosses"],
    ["Ruins of Kingsmarch", "boss", "Expedition", "The Aberration"],
    ["Verisium Crater", "boss", "Expedition", "The Aberration"],
    ["Atlas", "town", "", "Atlas UI"]
  ],
  internalHints: [
    ["Hideout", "hideout"],
    ["Delirium_", "special"],
    ["Citadel", "boss"],
    ["BurningMonolith", "boss"],
    ["Monolith", "boss"],
    ["OriginTower", "boss"],
    ["Realmgate", "boss"],
    ["TwistedDomain", "boss"],
    ["Crux", "boss"],
    ["BlackCathedral", "boss"],
    ["Atziri", "boss"],
    ["CaerTarth", "boss"],
    ["Kingsmarch", "boss"],
    ["SecludedTemple", "boss"],
    ["ObscureIsland", "boss"],
    ["FallenKing", "boss"],
    ["FallenStar", "boss"],
    ["VerisiumCrater", "boss"],
    ["Uhtred", "boss"],
    ["Olroth", "boss"],
    ["Vorana", "boss"],
    ["Medved", "boss"],
    ["Styrn", "boss"],
    ["Aberration", "boss"],
    ["WitheredHollow", "boss"],
    ["GrandExpedition", "expedition"],
    ["ExpeditionLogbook", "expedition"],
    ["Expedition_", "expedition"],
    ["BarrenAtoll", "expedition"],
    ["Castaway", "expedition"],
    ["CharredIsle", "expedition"],
    ["BleachedShoals", "expedition"],
    ["CraggyPeninsula", "expedition"],
    ["ExhumedRuins", "expedition"],
    ["FrigidBluffs", "expedition"],
    ["GrazedPrairy", "expedition"],
    ["MoorOfFallenSkies", "expedition"],
    ["MoorOfTheFallenSkies", "expedition"],
    ["MournfulCliffside", "boss"],
    ["ScorchedCay", "expedition"],
    ["SloughedGully", "expedition"],
    ["StagnantBasin", "expedition"],
    ["StoneAltar", "expedition"],
    ["TheOasis", "expedition"],
    ["VolcanicWarrens", "expedition"],
    ["Breach", "special"],
    ["Sanctum", "special"],
    ["Trial", "special"]
  ]
};
